# Application Name
spring.application.name=school-client-backend

# Server Configuration
server.port=8081

# Datasource (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/school_client_db
spring.datasource.username=postgres
spring.datasource.password=80097
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# For backend URLs
app.base-url=http://localhost:8081
# DevTools (optional, for hot reload)
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# JWT / Security (example)
jwt.secret=YourSecretKeyHere
jwt.expiration=3600000  # 1 hour in milliseconds

# Logging
logging.level.org.springframework=INFO
logging.level.com.example.demo=DEBUG


springdoc.api-docs.path=/api-documentation
springdoc.swagger-ui.path=/api-documentation

cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false